/* Copyright 2021 Glorious, LLC <salman@pcgamingrace.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

/* USB */
#define MANUFACTURER "APOS40"
#define PRODUCT "APOS40"
#define VENDOR_ID 0x6260
#define PRODUCT_ID 0x6393
#define DEVICE_VER 0x0001
#define FORCE_NKRO
#define USB_SUSPEND_WAKEUP_DELAY 1000

#define ENCODERS_PAD_A { A15, B4 }
#define ENCODERS_PAD_B { B3,  B5 }

/* Hold ESC on start up to clear EEPROM and boot into bootloader mode */
#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0

/* Multimode */
#ifdef MULTIMODE_ENABLE
#    define MM_USB_EN_PIN C13
#    define MM_USB_EN_STATE 0
#    define MM_USB_AUTO_SLEEP_DISABLE

#    define MM_BT1_NAME "APOS40 BT1"
#    define MM_BT2_NAME "APOS40 BT2"
#    define MM_BT3_NAME "APOS40 BT3"
#    define MM_DONGLE_PRODUCT "npkc 2.4G"

#    define RGB_MATRIX_BAT_INDEX_MAP {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
#    define IM_BAT_REQ_LEVEL1_COLOR RGB_RED
#    define IM_BAT_REQ_LEVEL2_COLOR RGB_RED
#    define IM_BAT_REQ_LEVEL3_COLOR RGB_RED

#    define MM_SLEEP_TIMEOUT (3 * 60000) // 2 min

#    define RGB_DRIVER_EN_PIN B13

#    define IM_LKEY_COUNT 4 // 用户自定义长按按键数量

#    define RGB_MATRIX_BLINK_COUNT 13
#    define RGB_MATRIX_BLINK_INDEX_BAT 2
#    define RGB_MATRIX_BLINK_INDEX_ALL 0xFF

#    define IM_MM_RGB_BLINK_INDEX_BT1 30
#    define IM_MM_RGB_BLINK_INDEX_BT2 31
#    define IM_MM_RGB_BLINK_INDEX_BT3 32
#    define IM_MM_RGB_BLINK_INDEX_2G4 33

#    define IM_MM_LBACK_TIMEOUT (30 * 1000)
#    define IM_MM_PAIR_TIMEOUT (30 * 1000)
#    define IM_MM_SUCCEED_TIME (2 * 1000)

#    define IM_MM_LBACK_COLOR_BT1 RGB_BLUE
#    define IM_MM_LBACK_COLOR_BT2 RGB_BLUE 
#    define IM_MM_LBACK_COLOR_BT3 RGB_BLUE
#    define IM_MM_LBACK_COLOR_2G4 RGB_YELLOW

#    define IM_MM_PAIR_COLOR_BT1 RGB_BLUE
#    define IM_MM_PAIR_COLOR_BT2 RGB_BLUE 
#    define IM_MM_PAIR_COLOR_BT3 RGB_BLUE
#    define IM_MM_PAIR_COLOR_2G4 RGB_YELLOW

#define IM_RGB_BAT_REQ_CLOSE_ALL

#endif

/*DCDC*/

#define POWER_DCDC_EN_PIN B13

#define BATTERY_CAPACITY_LOW 30
#define BATTERY_CAPACITY_STOP 0

#define IM_MM_INDICATOR_CAPS 28

/* UART */
#define SERIAL_DRIVER SD1
#define SD1_TX_PIN A9
#define SD1_RX_PIN A10
#define SELECT_SOFT_SERIAL_SPEED 1

/* DEBOUNCE */
#define DEBOUNCE 5
#define HOLD_ON_OTHER_KEY_PRESS

/* Key Matrix */
#define MATRIX_ROWS 4
#define MATRIX_COLS 12
#define DIODE_DIRECTION ROW2COL
#define MATRIX_COL_PINS \
    { C14, C15, B0, B1, B2, B10, B11, B9, B8, B7, B6, A0}
#define MATRIX_ROW_PINS \
    { A1, A2, A3, A4 }

/* SPI Config for LED Driver */
#define SPI_DRIVER SPIDQ
#define SPI_SCK_PIN A5
#define SPI_MOSI_PIN A7
#define SPI_MISO_PIN A6

/* Flash */
#define EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN B14
#define WEAR_LEVELING_BACKING_SIZE (4 * 1024)
#define WEAR_LEVELING_LOGICAL_SIZE (WEAR_LEVELING_BACKING_SIZE / 2)
#define FEE_PAGE_COUNT (WEAR_LEVELING_BACKING_SIZE / FEE_PAGE_SIZE)

/* RGB Matrix */
#define RGB_DI_PIN B15
#define WS2812_SPI SPIDM2
#define WS2812_SPI_DIVISOR 24

#define RGB_MATRIX_LED_COUNT (39+22)
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200
#define RGB_MATRIX_STARTUP_MODE 13
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_VAL_STEP 50
#define RGB_MATRIX_DEFAULT_VAL 200
#define RGB_MATRIX_SPD_STEP 65
#define RGB_MATRIX_DEFAULT_SPD 195

#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define RGB_TRIGGER_ON_KEYDOWN

/* RGB Lighting */
#define RGBLED_NUM 22

#define RGBLIGHT_LIMIT_VAL 100
#define RGBLIGHT_HUE_STEP 32
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 10
#define RGBLIGHT_DEFAULT_VAL 200
#define RGBLIGHT_DEFAULT_SPD 64
#define RGBLIGHT_SLEEP
#define RGBLIGHT_DEFAULT_MODE 14

#define LED_ARRAY led
#define RGBLIGHT_LED_MAP { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21}
/* 这个宏定义表示主灯和侧灯分别调节 */
#define RGBLIGHT_DISABLE_KEYCODES

/* RGB Lighting effects*/
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE

// RGB Matrix Animation modes. Explicitly enabled
// For full list of effects, see:
// https://docs.qmk.fm/#/feature_rgb_matrix?id=rgb-matrix-effects
#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_BAND_SAT
#define ENABLE_RGB_MATRIX_BAND_VAL
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_DUAL_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_HUE_BREATHING
#define ENABLE_RGB_MATRIX_HUE_PENDULUM
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_PIXEL_RAIN
#define ENABLE_RGB_MATRIX_PIXEL_FLOW
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
// enabled only if RGB_MATRIX_FRAMEBUFFER_EFFECTS is defined
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
// enabled only of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES is defined
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
